export const VNODE_TYPES = {
  ELEMENT: "ELEMENT",
  TEXT: "TEXT",
  COMPONENT: "COMPONENT",
};

export const VNODE_INTERNAL_TYPES = {
  TEXT_ELEMENT: "TEXT_ELEMENT",
};

export const PATCH_TYPES = {
  CREATE: "CREATE",
  REMOVE: "REMOVE",
  REPLACE: "REPLACE",
  UPDATE_PROP: "UPDATE_PROP",
  UPDATE_TEXT: "UPDATE_TEXT",
};
